# Generated by Django 5.1.6 on 2025-03-08 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamentoServicos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StatusEvento',
            new_name='StatusServico',
        ),
        migrations.RenameField(
            model_name='statusservico',
            old_name='status',
            new_name='statusEvento',
        ),
        migrations.AlterField(
            model_name='evento',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='horario',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
