# Generated by Django 5.1.6 on 2025-03-07 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StatusUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo')], default='Ativo', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CadastroUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('cpf', models.BigIntegerField(unique=True)),
                ('senha', models.CharField(max_length=50)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gerenciamentoUsuario.statususuario')),
            ],
            options={
                'verbose_name': 'CadastroUsuario',
                'verbose_name_plural': 'CadastroUsuarios',
                'db_table': 'CadastroUsuario',
            },
        ),
    ]
