# Generated by Django 5.1.6 on 2025-03-12 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamentoUsuario', '0002_alter_statususuario_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastrousuario',
            name='cpf',
            field=models.CharField(max_length=11),
        ),
    ]
