# Generated by Django 5.1.6 on 2025-03-12 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamentoUsuario', '0003_alter_cadastrousuario_cpf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastrousuario',
            name='senha',
        ),
        migrations.AddField(
            model_name='cadastrousuario',
            name='usuario_adm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cadastrousuario',
            name='usuario_comum',
            field=models.BooleanField(default=False),
        ),
    ]
