# Generated by Django 5.1.6 on 2025-03-07 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StatusLivro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Disponivel', 'Disponível'), ('Alugado', 'Alugado'), ('Reservado', 'Reservado'), ('Alugado e reservado', 'Alugado e Reservado')], default='disponivel', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=100)),
                ('ano', models.IntegerField()),
                ('edicao', models.IntegerField()),
                ('statusLuivro', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gerenciamentoLivro.statuslivro')),
            ],
            options={
                'verbose_name': 'Livro',
                'verbose_name_plural': 'Livros',
                'db_table': 'Livro',
            },
        ),
    ]
