# Generated by Django 5.1.6 on 2025-03-08 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamentoLivro', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livro',
            old_name='statusLuivro',
            new_name='statusLivro',
        ),
        migrations.AlterField(
            model_name='livro',
            name='ano',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='livro',
            name='edicao',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
